### PR TITLE
Told @gnarf

### PR DESCRIPTION
**Pull request by jacobroufa**
You said something in gnarf/osx-compose-key#17 ♫┗(＾0＾)┓♫

### CODE REVIEW

**Comment by jacobroufa** [comment]
😜

**Comment by chee** [comment]
We require contributors to sign our Contributor License Agreement, and we don't seem to have you on file.

**Comment by chee** [comment]
please read CONTRIBUTING.md before filing a pull request

**Comment by chee** [comment]
-1 no tests

**Pull request merged**
